services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ouoertheo/discord-habitica:latest
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ${VOLUME_MOUNT}:${PROJECT_DIR}/${STORE_DIR}
